### ISSUE TITLE
Maximum of nested Level in Navbar should be assigned by global config file.

### ISSUE THREAD

**Issue by mildronize** [dotnetthailand/dotnetthailand.github.io#131]
# Problem

As you can see in the code: [/src/components/Sidebar/contentTree.js](https://github.com/dotnetthailand/dotnetthailand.github.io/blob/a30ab60e34d220b2c2f19a33471555c627f5ef7c/src/components/Sidebar/contentTree.js#L12-L13)

```js
// ...
// Maximum Deep level of render Nav menu (Start with 0)
const limitDeepLevel = 3;
// ...
```

this setting is not assigned by global config file.

# Expected Behavior 

It should be assign in file `/config/config.yml`

```yml
# ...
features:
  sidebar: 
    limitDeepLevel: 3  # Maximum Deep level of render Nav menu (Start with 0)
# ...
```
